# ----------------------------
# Set ICON to the png icon file name
# Set DESCRIPTION to display within a compatible shell
# ----------------------------

ICON        ?= iconc.png
DESCRIPTION ?= "C SDK Demo"

# ----------------------------

# This is just so the main makefile in $CEDEV/examples makes this one be like "make debug"
.DEFAULT_GOAL := debug

include $(CEDEV)/bos/include/.makefile
