# ----------------------------
# Set ICON to the png icon file name
# Set DESCRIPTION to display within a compatible shell
# ----------------------------

ICON        ?= iconc.png
DESCRIPTION ?= "C SDK Demo"

# ----------------------------

include $(CEDEV)/bos/include/.makefile
